version: 2
jobs:
  build:
    working_directory: /go/src/github.com/dcarley/strava-commute
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
